#!/usr/bin/env python3
"""
bmp2icons.py — chuyển bộ icon .bmp (24-bit) sang header C cho TFT_eSPI.

Cách dùng:
    # Bộ icon lớn (50x50) → symbol dạng ICON_xxx, hàm weatherIconByName()
    python3 bmp2icons.py big/ ICON  > weather_icons.h

    # Bộ icon nhỏ (28x28) → symbol dạng ICONSM_xxx, hàm weatherIconSmByName()
    python3 bmp2icons.py small/ ICONSM  > weather_icons_sm.h

Tham số 2 (PREFIX) mặc định "ICON". Dùng prefix khác cho bộ thứ 2 để tránh
trùng tên mảng/enum/hàm khi include cả hai vào cùng sketch.

Yêu cầu: Pillow  (pip install Pillow)
"""
import sys, os, glob
from PIL import Image

def rgb888_to_565(r, g, b):
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)

def sym(name):
    return name.upper().replace("-", "_").replace(" ", "_")

def main():
    if len(sys.argv) < 2:
        sys.stderr.write("Usage: python3 bmp2icons.py <folder> [PREFIX]  > out.h\n")
        sys.exit(1)

    folder = sys.argv[1]
    prefix = sys.argv[2] if len(sys.argv) > 2 else "ICON"
    P = prefix.upper()
    files = sorted(glob.glob(os.path.join(folder, "*.bmp")))
    if not files:
        sys.stderr.write(f"Khong tim thay .bmp trong {folder}\n")
        sys.exit(1)

    W = H = None
    icons = []  # (symbol, basename, [uint16...])

    for path in files:
        base = os.path.splitext(os.path.basename(path))[0]
        im = Image.open(path).convert("RGB")
        w, h = im.size
        if W is None:
            W, H = w, h
        elif (w, h) != (W, H):
            sys.stderr.write(f"CANH BAO: {base} co size {w}x{h} khac {W}x{H}, bo qua.\n")
            continue
        px = im.load()
        data = []
        for y in range(h):          # Pillow đã chuẩn hoá top-down, không cần lật
            for x in range(w):
                r, g, b = px[x, y]
                data.append(rgb888_to_565(r, g, b))
        icons.append((sym(base), base, data))

    out = sys.stdout
    out.write("#pragma once\n")
    out.write(f"// Auto-generated by bmp2icons.py (prefix={P}) — DO NOT EDIT BY HAND.\n")
    out.write("#include <stdint.h>\n")
    out.write("#include <pgmspace.h>\n")
    out.write("#include <string.h>\n\n")
    out.write(f"#define {P}_W {W}\n#define {P}_H {H}\n\n")

    for symbol, base, data in icons:
        out.write(f"// {base}.bmp\n")
        out.write(f"const uint16_t {P}_{symbol}[{W*H}] PROGMEM = {{\n")
        for i in range(0, len(data), 12):
            row = ", ".join(f"0x{v:04X}" for v in data[i:i+12])
            out.write(f"  {row},\n")
        out.write("};\n\n")

    # Bảng tra + hàm. Tên hàm gắn theo prefix để các bộ không đụng nhau:
    #   ICON   -> weatherIconByName
    #   ICONSM -> weatherIconSmByName
    #   MOON   -> moonByName   (hay <prefix viết thường>ByName cho prefix khác)
    if P == "ICON":
        fn = "weatherIconByName"
    elif P == "ICONSM":
        fn = "weatherIconSmByName"
    else:
        fn = P.lower() + "ByName"
    tbl = f"{P}_TABLE"
    cnt = f"{P}_COUNT"
    out.write(f"struct {P}Entry {{ const char* name; const uint16_t* data; }};\n")
    out.write(f"static const {P}Entry {tbl}[] = {{\n")
    for symbol, base, _ in icons:
        out.write(f'  {{ "{base}", {P}_{symbol} }},\n')
    out.write("};\n")
    out.write(f"static const int {cnt} = sizeof({tbl})/sizeof({tbl}[0]);\n\n")

    out.write("// Tra icon theo ten file (khong .bmp). Tra ve nullptr neu khong co.\n")
    out.write(f"static inline const uint16_t* {fn}(const char* name) {{\n")
    out.write(f"  for (int i = 0; i < {cnt}; i++)\n")
    out.write(f"    if (strcmp({tbl}[i].name, name) == 0) return {tbl}[i].data;\n")
    out.write("  return nullptr;\n")
    out.write("}\n")

    sys.stderr.write(f"OK: {len(icons)} icon {W}x{H} prefix={P}, "
                     f"~{W*H*2*len(icons)//1024} KB flash.\n")

if __name__ == "__main__":
    main()

